PREFIX ex: <http://rdf.biosemantics.org/xml2rdf/>
PREFIX acan: <http://acandonorway.github.com/XmlToRdf/ontology.ttl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?predicateIRI ?arrowStyleAttribute ?rangeId ?rangeIRI ?rangeStyleAttribute WHERE { 
    
    VALUES (?instanceId) {("INPUT_ID")}
    
    ?arrow a ex:mxCell;           
           ex:style ?arrowStyleAttribute;           
           ex:id ?arrowId;            
           ex:target ?rangeId;
           ex:source ?instanceId.
    FILTER regex(str(?arrowStyleAttribute), "endArrow")
    
    ?arrowChild ex:parent ?arrowId.           
      
    ?arrowAnnotation acan:hasChild ?arrowChild;          
                     a ex:UserObject;          
                     ex:link ?predicateLink.
    
    ?range ex:id ?rangeId;        
           a ex:UserObject;
          acan:hasChild [ex:style ?rangeStyleAttribute].
    
    OPTIONAL {
                  
    	?range ex:link ?rangeLink;
    }
    
    BIND(IRI(?predicateLink) AS ?predicateIRI)
    BIND(IRI(?rangeLink) AS ?rangeIRI)
    
    FILTER (?predicateIRI != rdf:type)
    
}
